### ISSUE TITLE
Home screen 

### ISSUE THREAD

**Issue by Deveshshankar** [bithyve/bitcointribe#6424]
Not as per the design 
1) Colors are looking super pale in the Tribe dev app that came out today morning.
2) Seeing this for the first time, the color is changing with the viewing angle! We've achieved iridescence in our app

![Screenshot_2023-02-27-10-27-21-60_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/221840044-189c049a-d82e-4311-aac7-b53b7733e284.jpg)

Design
<img width="244" alt="Screenshot 2023-02-27 at 11 05 34 AM" src="https://user-images.githubusercontent.com/107177634/221840208-c68267ac-35f5-41f4-ac0a-3815ec1e0111.png">

**Comment by Deveshshankar** [comment]
Check recording @Pawan2792 Uploading VID-20230227-WA0005.mp4…

**Comment by raihankhan-rk** [comment]
Hi everyone! I was going through the issues since I plan to contribute to BitcoinTribe this SoB. I came across this issue and would like to suggest something If everyone is okay with it.
I think blue or green would be more appropriate for the app, as blue is associated with finance and signifies a sense of trust among users. We'd want our users to trust our wallet and that their money is safe in Hexa Wallet! 
Feel free to ignore my suggestions if you feel them to be out of context.

**Comment by Deveshshankar** [comment]
Not accurate as per design but it can go
